### ISSUE TITLE
Deus Ex: Mankind Divided doesn't start

### ISSUE THREAD

**Issue by jqadev** [HansKristian-Work/vkd3d#122]
### Software information
The game doesn't start when `VKD3D_FEATURE_LEVEL=12_0 %command%` is set and when isn't.
The launcher starts.

This is a game with the smallest FPS number I have so I set the lowest possible preset as I play on notebook and as results are very weak:
* native OpenGL version (~ 10 FPS)
* DXVK (D3D11) (~ 5 FPS)

I decided to test it with vkd3d as there is an option to enable DX12 in the settings but it doesn't start.
![image](https://user-images.githubusercontent.com/20422423/82264331-030aaf80-9965-11ea-815c-452d0dd81db2.png)

### [System information (gist)](https://gist.github.com/jqadev/8a892c8f8b5145169b4d5ae8c142c7c9) 
- Distro: Ubuntu 20.04 LTS
- GPU: GeForce 930MX
- Driver: NVIDIA 440.64
- Proton version: 5.0-7

### Log files
- [steam-337000-VKD3D_FEATURE_LEVEL=12_0.log](https://github.com/HansKristian-Work/vkd3d/files/4647651/steam-337000-VKD3D_FEATURE_LEVEL.12_0.log)
(collected using `PROTON_LOG=1 VKD3D_FEATURE_LEVEL=12_0 %command%`)
- [steam-337000.log](https://github.com/HansKristian-Work/vkd3d/files/4647598/steam-337000.log) (collected using `PROTON_LOG=1 %command%`)

**Comment by doitsujin** [comment]
Not a vkd3d bug, you need the native d3dcompiler_47 library.

**Comment by jqadev** [comment]
@doitsujin, @aeikum do you know when we can expect this native d3dcompiler_47 library out of the box in Proton?
