### ISSUE TITLE
Deus Ex: Mankind Divided crashes - vkd3d failed to allocate device memory

### ISSUE THREAD

**Issue by jqadev** [HansKristian-Work/vkd3d#124]
### Software information
@doitsujin according to your answer https://github.com/HansKristian-Work/vkd3d/issues/122#issuecomment-630757866 I found here https://www.protondb.com/app/449610 that I can download d3dcompiler_47 library from here https://lutris.net/files/tools/dll/d3dcompiler_47.dll
so I put it to `~/.steam/debian-installation/steamapps/common/Deus Ex Mankind Divided/retail` and the game started to work but it crashes when I press the space button to continue the story
![Screenshot from 2020-05-25 18-18-02](https://user-images.githubusercontent.com/20422423/82831534-f2a08a80-9eb8-11ea-8706-df650673d088.png)

### [System information (gist)](https://gist.github.com/jqadev/8a892c8f8b5145169b4d5ae8c142c7c9) 
- Distro: Ubuntu 20.04 LTS
- GPU: GeForce 930MX
- Driver: NVIDIA 440.64
- Proton version: 5.0-7

### Log files
- [steam-337000.zip](https://github.com/HansKristian-Work/vkd3d/files/4678193/steam-337000.zip) (collected using `PROTON_LOG=1 %command%`)

**Comment by doitsujin** [comment]
> warn:vkd3d_allocate_device_memory: Failed to allocate device memory, vr -2.
warn:hresult_from_vk_result: Out of device memory.

Your GPU doesn't have enough VRAM, and vkd3d currently does not handle this at all.

**Comment by jqadev** [comment]
@doitsujin DXVK handles that because I can run the game using it as I wrote here https://github.com/HansKristian-Work/vkd3d/issues/122#issue-620542247. 
Are there any plans to handle that in vkd3d as well? 
If no, please close this issue.

**Comment by doitsujin** [comment]
> Are there any plans to handle that in vkd3d as well?

Yes, but it requires a rewrite of the memory allocation logic.

**Comment by jqadev** [comment]
@doitsujin congrats on you great work here https://github.com/HansKristian-Work/vkd3d/pull/132 :+1: 
Do you have some CI/CD like this https://git.froggi.es/joshua/dxvk/-/jobs?
I would like to test master containing recently merged commits.

**Comment by jqadev** [comment]
@doitsujin I tested the game against https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-2-MF containing https://github.com/HansKristian-Work/vkd3d/pull/132 and it doesn't crash anymore. Thanks :+1:
