### ISSUE TITLE
Where do I find 1.1.140 headers

### ISSUE THREAD

**Issue by SteveEbey73742** [HansKristian-Work/vkd3d#128]
Clean git pull, go to compile, and get the error that I need 1.1.140 headers. The latest download of the vulkan sdk is 1.1.135, so please link the location I need to download the new headers

**Comment by doitsujin** [comment]
Headers are available from https://github.com/KhronosGroup/Vulkan-Headers, ideally your distro should provide them.

**Comment by HansKristian-Work** [comment]
Arch provides them, but it might be easier to just start using Vulkan-Headers as submodules.

**Comment by SveSop** [comment]
Technically it is 1.2.140 headers that you can download... but anyway :)

**Comment by SteveEbey73742** [comment]
got them installed, compiled the hk version, added the patches to wine,
removed optimizations, compiled only 64 bit, and now it crashes with error
#132, memory could not be read.

**Comment by HansKristian-Work** [comment]
> Technically it is 1.2.140 headers that you can download... but anyway :)

Fixed now.

**Comment by HansKristian-Work** [comment]
> and now it crashes with error #132, memory could not be read.

Do you have a more complete log? That doesn't tell us much. Either way, closing this issue as it's not really vkd3d related. If you get a log for your crash, please open another issue.
