### ISSUE TITLE
question: what are the requirements for vkd3d

### ISSUE THREAD

**Issue by logan001** [HansKristian-Work/vkd3d#140]
Sorry to ask this here but i can't find anything on google (at least not in the first 3 pages)
what are the requirements for vkd3d to work. i have a 970 gtx that works in windows 10 with dx12 but on proton it doesn't work. on wine i've tried the unreal engine demo that seems to work with a few glitches but other game says that i have no dx12 available on the same wine.
so do i have something missing? my arch is broken? or this video card is not supported?

i have 440.66.15 driver installed.

wine is from pkgbuilds (default configuration) and i've tried a proton version from pkg but still no success

**Comment by HansKristian-Work** [comment]
Vulkan 1.1 and VK_KHR_timeline_semaphore is required. Other than that, there shouldn't be any particularly steep requirements.

**Comment by SveSop** [comment]
@logan001 Probably a lot of DX12 games/demos that does not work with vkd3d as of now. It is kind of unspecific to say "other game", cos that does not tell much.

440.66.15 works currently with my RTX2070 and World of Warcraft d3d12. Aside from the particular raytracing things, there is not much difference in vulkan support between the 970 and the 2070 card afaik.

You can check VK_KHR_timeline_semaphore support by typing:
`vulkaninfo |grep VK_KHR_timeline_semaphore`
This should read:
`VK_KHR_timeline_semaphore                 : extension revision 2`
for your card :)

**Comment by logan001** [comment]
@SveSop well that what is says for me too `revision 2`
as for the game that i've tried in proton is deus ex mankind blahblah. if set to dx12 will exit after the launcher. using tkgproton will not even show dx12 in settings.
i've tried also the trial of tomb raider - shadow of blahblah but again it exits right after the launcher.

**Comment by SveSop** [comment]
SOTTR should work tho, but i don't know if the trial is some different version/crippled/whatever so that it is different in some way?

Just to make sure, since it's easy to miss something. When you say tkgproton, i assume you compile yourself.... you do have all the libvkd3d libraries installed, and proton configure does not complain about anything there? (Sorry, but i do not use Arch, so i am a bit unfamiliar with the pkgbuild system and such tho).

Running things like "gears-vkd3d" (depending on your distro naming scheme and installation of the demo's). Does that work? :)

**Comment by logan001** [comment]
i just "installed" WoW since its free and seems that the game works detects dx12 by default and works...at least the starting town (man that graphic is so ancient)
i do have libvkd3d
i've tried also rise of the tomb raider (i had no clue it has dx12) and tried a benchmark with "dx12". 1st scene of the benchmark works. after that the game freeze so no luck after. but at least proton finally started a game with vkd3d. trying to load some saved point freeze the game.
At least i manage to make 1 game work with vkd3d :)
