### ISSUE TITLE
RE2: Horribly glitched rendering on NV

### ISSUE THREAD

**Issue by HansKristian-Work** [HansKristian-Work/vkd3d#42]
GTX 1660 Ti, driver 440.58.02.

The game uses vkCmdMultiDrawIndirect and friends, and it renders the wrong data somehow.

Oddly enough, capturing the game with RenderDoc, the game renders fine.
I've tried forcefully adding barriers and waitforidles everywhere to no avail.

**Comment by HansKristian-Work** [comment]
A good lead right now is a potential driver bug around indirect count where the indirect count is not clamped to maxDrawCount.

**Comment by HansKristian-Work** [comment]
Confirmed with various tests that this is a driver bug, not vkd3d.

**Comment by SveSop** [comment]
I saw 440.66.04 was posted yesterday.. Vulkan beta tho, but probably leaps ahead of 440.58.x series :)

**Comment by HansKristian-Work** [comment]
Not really, 440.58.x is quite recent. It's been confirmed to be a driver bug in the NV driver, so probably next beta driver or something will have a fix.

**Comment by HansKristian-Work** [comment]
Solved in latest beta driver as of April 1.
